/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"

#include "my_led.h"
//#include "my_switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void switch_init()
{
	RCC-> AHB1ENR |=BV(0);
	GPIOA->MODER &= ~(BV(0)|BV(1));
	//GPIOA->OTYPER &= ~(BV(0));
	GPIOA->OSPEEDR &= ~(BV(0)|BV(1));
	GPIOA ->PUPDR &= ~(BV(0)|BV(1));
}

int is_switch_press()
{
	return (BV(0) & GPIOA ->IDR) == 1?1:0;
}



int main(void)
{
    int led = 0;
	led_init();
	switch_init();


	while(1)
	{
		if(is_switch_press())
		{
		led++;
		if(led > 4)
		{
			led=1;
		}
		//turn off all leds
		GREEN_led_off();
		ORANGE_led_off();
		RED_led_off();
		BLUE_led_off();
		//turn on only one led
		if(led==1)
		{
			GREEN_led_on();
		}else if(led==2)
		{
			ORANGE_led_on();
		}
		else if(led==3)
		{
			RED_led_on();
		}else if(led==4)
		{
			BLUE_led_on();
		}
		//wait until switch is released
		while(is_switch_press());
		DelayMs(50);
}
}
}

