/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"my_led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void switch_init()
{
	//switch Initalisation
	//Enable clock for GPIOA
	RCC->AHB1ENR |= BV(0);

	//Set GPIO A0 as input
	GPIOA->MODER &= ~(BV(1) | BV(0));

	//Set GPIO A0 as low speed
	GPIOA->OSPEEDR &= ~(BV(1) | BV(0));

	//Set GPIO A0 as no pull up no pull down
	GPIOA->PUPDR &= ~(BV(1) | BV(0));
}
int is_switch_press()
{
	//Check if switch is pressed or not
	return  (BV(0) & GPIOA->IDR)  == 1 ? 1 : 0 ;
}


int main(void)
{

	led_init();
	switch_init();
	int led=0;


	while(1)
	{
		//Check if switch is pressed or not
				if( is_switch_press() )
	{
		Green_led_on();
		DelayMs(1000);
		Green_led_off();
		Orange_led_on();
		DelayMs(1000);
		Red_led_on();
		DelayMs(1000);
		Blue_led_on();
		DelayMs(1000);

		//turn off one by one

		Blue_led_off();
		DelayMs(1000);
		Red_led_off();
	    DelayMs(1000);
	    Orange_led_off();
	    DelayMs(1000);
	    Green_led_off();
	    DelayMs(1000);

	}
	}



}

